# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def ClassifyLinks(self, links: str,party_name: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.LinkClassification"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ClassifyLinks(links=links,party_name=party_name,context=context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyLinks", args={
                "links": links,"party_name": party_name,"context": context,
            })
            return typing.cast(typing.List["types.LinkClassification"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ClassifyPage(self, html_excerpt: str,current_url: str,party_name: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PageClassification:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ClassifyPage(html_excerpt=html_excerpt,current_url=current_url,party_name=party_name,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyPage", args={
                "html_excerpt": html_excerpt,"current_url": current_url,"party_name": party_name,
            })
            return typing.cast(types.PageClassification, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MinutesBoundary:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DetectBoundary(minutes_text=minutes_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DetectBoundary", args={
                "minutes_text": minutes_text,
            })
            return typing.cast(types.MinutesBoundary, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SectionInfo"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DivideMinutesToKeywords(minutes=minutes,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DivideMinutesToKeywords", args={
                "minutes": minutes,
            })
            return typing.cast(typing.List["types.SectionInfo"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SpeakerAndSpeechContent"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DivideSpeech(section_string=section_string,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DivideSpeech", args={
                "section_string": section_string,
            })
            return typing.cast(typing.List["types.SpeakerAndSpeechContent"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AttendeesMapping:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractAttendees(attendees_text=attendees_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractAttendees", args={
                "attendees_text": attendees_text,
            })
            return typing.cast(types.AttendeesMapping, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ExtractedMember"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractMembers(html=html,conference_name=conference_name,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractMembers", args={
                "html": html,"conference_name": conference_name,
            })
            return typing.cast(typing.List["types.ExtractedMember"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ParliamentaryGroupMember"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractParliamentaryGroupMembers(html=html,text_content=text_content,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractParliamentaryGroupMembers", args={
                "html": html,"text_content": text_content,
            })
            return typing.cast(typing.List["types.ParliamentaryGroupMember"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractRoleNameMapping(self, attendee_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoleNameMappingResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractRoleNameMapping(attendee_text=attendee_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractRoleNameMapping", args={
                "attendee_text": attendee_text,
            })
            return typing.cast(types.RoleNameMappingResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def MatchPolitician(self, speaker_name: str,speaker_type: str,speaker_party: str,available_politicians: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PoliticianMatch:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.MatchPolitician(speaker_name=speaker_name,speaker_type=speaker_type,speaker_party=speaker_party,available_politicians=available_politicians,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="MatchPolitician", args={
                "speaker_name": speaker_name,"speaker_type": speaker_type,"speaker_party": speaker_party,"available_politicians": available_politicians,
            })
            return typing.cast(types.PoliticianMatch, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def NormalizeSpeakerNames(self, speakers: typing.List[str],role_name_mappings: typing.Optional[typing.Dict[str, str]] = None,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.NormalizedSpeaker"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.NormalizeSpeakerNames(speakers=speakers,role_name_mappings=role_name_mappings,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="NormalizeSpeakerNames", args={
                "speakers": speakers,"role_name_mappings": role_name_mappings,
            })
            return typing.cast(typing.List["types.NormalizedSpeaker"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SectionInfo"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.RedivideSection(section_text=section_text,divide_counter=divide_counter,original_index=original_index,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="RedivideSection", args={
                "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
            })
            return typing.cast(typing.List["types.SectionInfo"], __result__.cast_to(types, types, stream_types, False, __runtime__))



class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyLinks(self, links: str,party_name: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.LinkClassification"], typing.List["types.LinkClassification"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyLinks", args={
            "links": links,"party_name": party_name,"context": context,
        })
        return baml_py.BamlStream[typing.List["stream_types.LinkClassification"], typing.List["types.LinkClassification"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.LinkClassification"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.LinkClassification"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyPage(self, html_excerpt: str,current_url: str,party_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PageClassification, types.PageClassification]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyPage", args={
            "html_excerpt": html_excerpt,"current_url": current_url,"party_name": party_name,
        })
        return baml_py.BamlStream[stream_types.PageClassification, types.PageClassification](
          __result__,
          lambda x: typing.cast(stream_types.PageClassification, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PageClassification, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MinutesBoundary, types.MinutesBoundary]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DetectBoundary", args={
            "minutes_text": minutes_text,
        })
        return baml_py.BamlStream[stream_types.MinutesBoundary, types.MinutesBoundary](
          __result__,
          lambda x: typing.cast(stream_types.MinutesBoundary, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MinutesBoundary, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DivideMinutesToKeywords", args={
            "minutes": minutes,
        })
        return baml_py.BamlStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.SectionInfo"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.SectionInfo"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.SpeakerAndSpeechContent"], typing.List["types.SpeakerAndSpeechContent"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DivideSpeech", args={
            "section_string": section_string,
        })
        return baml_py.BamlStream[typing.List["stream_types.SpeakerAndSpeechContent"], typing.List["types.SpeakerAndSpeechContent"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.SpeakerAndSpeechContent"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.SpeakerAndSpeechContent"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AttendeesMapping, types.AttendeesMapping]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractAttendees", args={
            "attendees_text": attendees_text,
        })
        return baml_py.BamlStream[stream_types.AttendeesMapping, types.AttendeesMapping](
          __result__,
          lambda x: typing.cast(stream_types.AttendeesMapping, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AttendeesMapping, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.ExtractedMember"], typing.List["types.ExtractedMember"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractMembers", args={
            "html": html,"conference_name": conference_name,
        })
        return baml_py.BamlStream[typing.List["stream_types.ExtractedMember"], typing.List["types.ExtractedMember"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.ExtractedMember"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ExtractedMember"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.ParliamentaryGroupMember"], typing.List["types.ParliamentaryGroupMember"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractParliamentaryGroupMembers", args={
            "html": html,"text_content": text_content,
        })
        return baml_py.BamlStream[typing.List["stream_types.ParliamentaryGroupMember"], typing.List["types.ParliamentaryGroupMember"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.ParliamentaryGroupMember"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ParliamentaryGroupMember"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractRoleNameMapping(self, attendee_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RoleNameMappingResult, types.RoleNameMappingResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractRoleNameMapping", args={
            "attendee_text": attendee_text,
        })
        return baml_py.BamlStream[stream_types.RoleNameMappingResult, types.RoleNameMappingResult](
          __result__,
          lambda x: typing.cast(stream_types.RoleNameMappingResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RoleNameMappingResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def MatchPolitician(self, speaker_name: str,speaker_type: str,speaker_party: str,available_politicians: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PoliticianMatch, types.PoliticianMatch]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="MatchPolitician", args={
            "speaker_name": speaker_name,"speaker_type": speaker_type,"speaker_party": speaker_party,"available_politicians": available_politicians,
        })
        return baml_py.BamlStream[stream_types.PoliticianMatch, types.PoliticianMatch](
          __result__,
          lambda x: typing.cast(stream_types.PoliticianMatch, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PoliticianMatch, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def NormalizeSpeakerNames(self, speakers: typing.List[str],role_name_mappings: typing.Optional[typing.Dict[str, str]] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.NormalizedSpeaker"], typing.List["types.NormalizedSpeaker"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="NormalizeSpeakerNames", args={
            "speakers": speakers,"role_name_mappings": role_name_mappings,
        })
        return baml_py.BamlStream[typing.List["stream_types.NormalizedSpeaker"], typing.List["types.NormalizedSpeaker"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.NormalizedSpeaker"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.NormalizedSpeaker"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="RedivideSection", args={
            "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
        })
        return baml_py.BamlStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.SectionInfo"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.SectionInfo"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ClassifyLinks(self, links: str,party_name: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyLinks", args={
            "links": links,"party_name": party_name,"context": context,
        }, mode="request")
        return __result__
    async def ClassifyPage(self, html_excerpt: str,current_url: str,party_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyPage", args={
            "html_excerpt": html_excerpt,"current_url": current_url,"party_name": party_name,
        }, mode="request")
        return __result__
    async def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectBoundary", args={
            "minutes_text": minutes_text,
        }, mode="request")
        return __result__
    async def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DivideMinutesToKeywords", args={
            "minutes": minutes,
        }, mode="request")
        return __result__
    async def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DivideSpeech", args={
            "section_string": section_string,
        }, mode="request")
        return __result__
    async def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractAttendees", args={
            "attendees_text": attendees_text,
        }, mode="request")
        return __result__
    async def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractMembers", args={
            "html": html,"conference_name": conference_name,
        }, mode="request")
        return __result__
    async def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractParliamentaryGroupMembers", args={
            "html": html,"text_content": text_content,
        }, mode="request")
        return __result__
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    async def ExtractRoleNameMapping(self, attendee_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractRoleNameMapping", args={
            "attendee_text": attendee_text,
        }, mode="request")
        return __result__
    async def MatchPolitician(self, speaker_name: str,speaker_type: str,speaker_party: str,available_politicians: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MatchPolitician", args={
            "speaker_name": speaker_name,"speaker_type": speaker_type,"speaker_party": speaker_party,"available_politicians": available_politicians,
        }, mode="request")
        return __result__
    async def NormalizeSpeakerNames(self, speakers: typing.List[str],role_name_mappings: typing.Optional[typing.Dict[str, str]] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="NormalizeSpeakerNames", args={
            "speakers": speakers,"role_name_mappings": role_name_mappings,
        }, mode="request")
        return __result__
    async def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RedivideSection", args={
            "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
        }, mode="request")
        return __result__


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ClassifyLinks(self, links: str,party_name: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyLinks", args={
            "links": links,"party_name": party_name,"context": context,
        }, mode="stream")
        return __result__
    async def ClassifyPage(self, html_excerpt: str,current_url: str,party_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyPage", args={
            "html_excerpt": html_excerpt,"current_url": current_url,"party_name": party_name,
        }, mode="stream")
        return __result__
    async def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectBoundary", args={
            "minutes_text": minutes_text,
        }, mode="stream")
        return __result__
    async def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DivideMinutesToKeywords", args={
            "minutes": minutes,
        }, mode="stream")
        return __result__
    async def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DivideSpeech", args={
            "section_string": section_string,
        }, mode="stream")
        return __result__
    async def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractAttendees", args={
            "attendees_text": attendees_text,
        }, mode="stream")
        return __result__
    async def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractMembers", args={
            "html": html,"conference_name": conference_name,
        }, mode="stream")
        return __result__
    async def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractParliamentaryGroupMembers", args={
            "html": html,"text_content": text_content,
        }, mode="stream")
        return __result__
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    async def ExtractRoleNameMapping(self, attendee_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractRoleNameMapping", args={
            "attendee_text": attendee_text,
        }, mode="stream")
        return __result__
    async def MatchPolitician(self, speaker_name: str,speaker_type: str,speaker_party: str,available_politicians: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MatchPolitician", args={
            "speaker_name": speaker_name,"speaker_type": speaker_type,"speaker_party": speaker_party,"available_politicians": available_politicians,
        }, mode="stream")
        return __result__
    async def NormalizeSpeakerNames(self, speakers: typing.List[str],role_name_mappings: typing.Optional[typing.Dict[str, str]] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="NormalizeSpeakerNames", args={
            "speakers": speakers,"role_name_mappings": role_name_mappings,
        }, mode="stream")
        return __result__
    async def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RedivideSection", args={
            "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
        }, mode="stream")
        return __result__


b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))
