# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

from . import stream_types, types
from .runtime import BamlCallOptions, DoNotUseDirectlyCallManager


class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMembers(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> list["types.ExtractedMember"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractMembers", llm_response=llm_response, mode="request"
        )
        return typing.cast(list["types.ExtractedMember"], result)

    def ExtractResume(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractResume", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.Resume, result)


class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMembers(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> list["stream_types.ExtractedMember"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractMembers", llm_response=llm_response, mode="stream"
        )
        return typing.cast(list["stream_types.ExtractedMember"], result)

    def ExtractResume(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractResume", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.Resume, result)
