# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (15)
# #########################################################################

class AttendeesMapping(BaseModel):
    attendees_mapping: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    regular_attendees: typing.List[str]
    confidence: typing.Optional[float] = None

class ConfidenceJudgement(BaseModel):
    confidence: typing.Optional[float] = None
    confidence_level: typing.Optional[str] = None
    should_match: typing.Optional[bool] = None
    reason: typing.Optional[str] = None
    contributing_factors: typing.List["ContributingFactor"]
    recommendation: typing.Optional[str] = None

class ContributingFactor(BaseModel):
    factor: typing.Optional[str] = None
    impact: typing.Optional[float] = None
    description: typing.Optional[str] = None

class ExtractedMember(BaseModel):
    name: typing.Optional[str] = None
    role: typing.Optional[str] = None
    party_name: typing.Optional[str] = None
    additional_info: typing.Optional[str] = None

class LinkClassification(BaseModel):
    url: typing.Optional[str] = None
    link_type: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    reason: typing.Optional[str] = None

class MinutesBoundary(BaseModel):
    boundary_found: typing.Optional[bool] = None
    boundary_text: typing.Optional[str] = None
    boundary_type: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    reason: typing.Optional[str] = None

class PageClassification(BaseModel):
    page_type: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    reason: typing.Optional[str] = None
    has_child_links: typing.Optional[bool] = None
    has_member_info: typing.Optional[bool] = None

class ParliamentaryGroupMember(BaseModel):
    name: typing.Optional[str] = None
    role: typing.Optional[str] = None
    party_name: typing.Optional[str] = None
    district: typing.Optional[str] = None
    additional_info: typing.Optional[str] = None

class PoliticianMatch(BaseModel):
    matched: typing.Optional[bool] = None
    politician_id: typing.Optional[int] = None
    politician_name: typing.Optional[str] = None
    political_party_name: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    reason: typing.Optional[str] = None

class RedividedSectionInfo(BaseModel):
    chapter_number: typing.Optional[int] = None
    sub_chapter_number: typing.Optional[int] = None
    keyword: typing.Optional[str] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class SectionInfo(BaseModel):
    chapter_number: typing.Optional[int] = None
    keyword: typing.Optional[str] = None

class SectionString(BaseModel):
    chapter_number: typing.Optional[int] = None
    sub_chapter_number: typing.Optional[int] = None
    section_string: typing.Optional[str] = None

class SpeakerAndSpeechContent(BaseModel):
    speaker: typing.Optional[str] = None
    speech_content: typing.Optional[str] = None
    chapter_number: typing.Optional[int] = None
    sub_chapter_number: typing.Optional[int] = None
    speech_order: typing.Optional[int] = None

class SpeakerMatch(BaseModel):
    matched: typing.Optional[bool] = None
    speaker_id: typing.Optional[int] = None
    speaker_name: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    reason: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
