# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

import typing_extensions
from pydantic import BaseModel

StreamStateValueT = typing.TypeVar("StreamStateValueT")


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (2)
# #########################################################################


class ExtractedMember(BaseModel):
    name: str | None = None
    role: str | None = None
    party_name: str | None = None
    additional_info: str | None = None


class Resume(BaseModel):
    name: str | None = None
    email: str | None = None
    experience: list[str]
    skills: list[str]


# #########################################################################
# Generated type aliases (0)
# #########################################################################
