# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MinutesBoundary:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.DetectBoundary(minutes_text=minutes_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="DetectBoundary", args={
                "minutes_text": minutes_text,
            })
            return typing.cast(types.MinutesBoundary, result.cast_to(types, types, stream_types, False, __runtime__))
    def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SectionInfo"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.DivideMinutesToKeywords(minutes=minutes,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="DivideMinutesToKeywords", args={
                "minutes": minutes,
            })
            return typing.cast(typing.List["types.SectionInfo"], result.cast_to(types, types, stream_types, False, __runtime__))
    def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SpeakerAndSpeechContent"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.DivideSpeech(section_string=section_string,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="DivideSpeech", args={
                "section_string": section_string,
            })
            return typing.cast(typing.List["types.SpeakerAndSpeechContent"], result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AttendeesMapping:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractAttendees(attendees_text=attendees_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAttendees", args={
                "attendees_text": attendees_text,
            })
            return typing.cast(types.AttendeesMapping, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ExtractedMember"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractMembers(html=html,conference_name=conference_name,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractMembers", args={
                "html": html,"conference_name": conference_name,
            })
            return typing.cast(typing.List["types.ExtractedMember"], result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ParliamentaryGroupMember"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractParliamentaryGroupMembers(html=html,text_content=text_content,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractParliamentaryGroupMembers", args={
                "html": html,"text_content": text_content,
            })
            return typing.cast(typing.List["types.ParliamentaryGroupMember"], result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, result.cast_to(types, types, stream_types, False, __runtime__))
    def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.SectionInfo"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.RedivideSection(section_text=section_text,divide_counter=divide_counter,original_index=original_index,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="RedivideSection", args={
                "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
            })
            return typing.cast(typing.List["types.SectionInfo"], result.cast_to(types, types, stream_types, False, __runtime__))



class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MinutesBoundary, types.MinutesBoundary]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="DetectBoundary", args={
            "minutes_text": minutes_text,
        })
        return baml_py.BamlSyncStream[stream_types.MinutesBoundary, types.MinutesBoundary](
          result,
          lambda x: typing.cast(stream_types.MinutesBoundary, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MinutesBoundary, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="DivideMinutesToKeywords", args={
            "minutes": minutes,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.SectionInfo"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.SectionInfo"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.SpeakerAndSpeechContent"], typing.List["types.SpeakerAndSpeechContent"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="DivideSpeech", args={
            "section_string": section_string,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.SpeakerAndSpeechContent"], typing.List["types.SpeakerAndSpeechContent"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.SpeakerAndSpeechContent"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.SpeakerAndSpeechContent"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AttendeesMapping, types.AttendeesMapping]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAttendees", args={
            "attendees_text": attendees_text,
        })
        return baml_py.BamlSyncStream[stream_types.AttendeesMapping, types.AttendeesMapping](
          result,
          lambda x: typing.cast(stream_types.AttendeesMapping, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AttendeesMapping, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.ExtractedMember"], typing.List["types.ExtractedMember"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractMembers", args={
            "html": html,"conference_name": conference_name,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.ExtractedMember"], typing.List["types.ExtractedMember"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.ExtractedMember"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ExtractedMember"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.ParliamentaryGroupMember"], typing.List["types.ParliamentaryGroupMember"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractParliamentaryGroupMembers", args={
            "html": html,"text_content": text_content,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.ParliamentaryGroupMember"], typing.List["types.ParliamentaryGroupMember"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.ParliamentaryGroupMember"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ParliamentaryGroupMember"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          result,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="RedivideSection", args={
            "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.SectionInfo"], typing.List["types.SectionInfo"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.SectionInfo"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.SectionInfo"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetectBoundary", args={
            "minutes_text": minutes_text,
        }, mode="request")
        return result
    def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DivideMinutesToKeywords", args={
            "minutes": minutes,
        }, mode="request")
        return result
    def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DivideSpeech", args={
            "section_string": section_string,
        }, mode="request")
        return result
    def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttendees", args={
            "attendees_text": attendees_text,
        }, mode="request")
        return result
    def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMembers", args={
            "html": html,"conference_name": conference_name,
        }, mode="request")
        return result
    def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractParliamentaryGroupMembers", args={
            "html": html,"text_content": text_content,
        }, mode="request")
        return result
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return result
    def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RedivideSection", args={
            "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
        }, mode="request")
        return result


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectBoundary(self, minutes_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetectBoundary", args={
            "minutes_text": minutes_text,
        }, mode="stream")
        return result
    def DivideMinutesToKeywords(self, minutes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DivideMinutesToKeywords", args={
            "minutes": minutes,
        }, mode="stream")
        return result
    def DivideSpeech(self, section_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DivideSpeech", args={
            "section_string": section_string,
        }, mode="stream")
        return result
    def ExtractAttendees(self, attendees_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttendees", args={
            "attendees_text": attendees_text,
        }, mode="stream")
        return result
    def ExtractMembers(self, html: str,conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMembers", args={
            "html": html,"conference_name": conference_name,
        }, mode="stream")
        return result
    def ExtractParliamentaryGroupMembers(self, html: str,text_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractParliamentaryGroupMembers", args={
            "html": html,"text_content": text_content,
        }, mode="stream")
        return result
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return result
    def RedivideSection(self, section_text: str,divide_counter: int,original_index: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RedivideSection", args={
            "section_text": section_text,"divide_counter": divide_counter,"original_index": original_index,
        }, mode="stream")
        return result


b = BamlSyncClient(DoNotUseDirectlyCallManager({}))
