# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

import baml_py

from . import stream_types, type_builder, types
from .globals import (
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__,
)
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import BamlCallOptions, DoNotUseDirectlyCallManager


class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(
        self,
        tb: type_builder.TypeBuilder | None = None,
        client_registry: baml_py.baml_py.ClientRegistry | None = None,
        collector: baml_py.baml_py.Collector | list[baml_py.baml_py.Collector] | None = None,
        env: dict[str, str | None] | None = None,
        tags: dict[str, str] | None = None,
        on_tick: typing.Callable[[str, baml_py.baml_py.FunctionLog], None] | None = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
        return self.__stream_client

    @property
    def request(self):
        return self.__http_request

    @property
    def stream_request(self):
        return self.__http_stream_request

    @property
    def parse(self):
        return self.__llm_response_parser

    @property
    def parse_stream(self):
        return self.__llm_stream_parser

    def ExtractMembers(
        self,
        html: str,
        conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> list["types.ExtractedMember"]:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractMembers(
                html=html, conference_name=conference_name, baml_options=baml_options
            )
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractMembers",
                args={
                    "html": html,
                    "conference_name": conference_name,
                },
            )
            return typing.cast(
                list["types.ExtractedMember"],
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractResume(resume=resume, baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractResume",
                args={
                    "resume": resume,
                },
            )
            return typing.cast(
                types.Resume,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMembers(
        self,
        html: str,
        conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[
        list["stream_types.ExtractedMember"],
        list["types.ExtractedMember"],
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractMembers",
            args={
                "html": html,
                "conference_name": conference_name,
            },
        )
        return baml_py.BamlSyncStream[
            list["stream_types.ExtractedMember"],
            list["types.ExtractedMember"],
        ](
            result,
            lambda x: typing.cast(
                list["stream_types.ExtractedMember"],
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                list["types.ExtractedMember"],
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractResume",
            args={
                "resume": resume,
            },
        )
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
            result,
            lambda x: typing.cast(
                stream_types.Resume,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMembers(
        self,
        html: str,
        conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractMembers",
            args={
                "html": html,
                "conference_name": conference_name,
            },
            mode="request",
        )
        return result

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractResume",
            args={
                "resume": resume,
            },
            mode="request",
        )
        return result


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMembers(
        self,
        html: str,
        conference_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractMembers",
            args={
                "html": html,
                "conference_name": conference_name,
            },
            mode="stream",
        )
        return result

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractResume",
            args={
                "resume": resume,
            },
            mode="stream",
        )
        return result


b = BamlSyncClient(DoNotUseDirectlyCallManager({}))
