# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AttendeesMapping": types.AttendeesMapping,
    "stream_types.AttendeesMapping": stream_types.AttendeesMapping,

    "types.ExtractedMember": types.ExtractedMember,
    "stream_types.ExtractedMember": stream_types.ExtractedMember,

    "types.ExtractedPartyMember": types.ExtractedPartyMember,
    "stream_types.ExtractedPartyMember": stream_types.ExtractedPartyMember,

    "types.LinkClassification": types.LinkClassification,
    "stream_types.LinkClassification": stream_types.LinkClassification,

    "types.MinutesBoundary": types.MinutesBoundary,
    "stream_types.MinutesBoundary": stream_types.MinutesBoundary,

    "types.PageClassification": types.PageClassification,
    "stream_types.PageClassification": stream_types.PageClassification,

    "types.ParliamentaryGroupMember": types.ParliamentaryGroupMember,
    "stream_types.ParliamentaryGroupMember": stream_types.ParliamentaryGroupMember,

    "types.PoliticianMatch": types.PoliticianMatch,
    "stream_types.PoliticianMatch": stream_types.PoliticianMatch,

    "types.RedividedSectionInfo": types.RedividedSectionInfo,
    "stream_types.RedividedSectionInfo": stream_types.RedividedSectionInfo,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SectionInfo": types.SectionInfo,
    "stream_types.SectionInfo": stream_types.SectionInfo,

    "types.SectionString": types.SectionString,
    "stream_types.SectionString": stream_types.SectionString,

    "types.SpeakerAndSpeechContent": types.SpeakerAndSpeechContent,
    "stream_types.SpeakerAndSpeechContent": stream_types.SpeakerAndSpeechContent,

    "types.SpeakerMatch": types.SpeakerMatch,
    "stream_types.SpeakerMatch": stream_types.SpeakerMatch,


}
