# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import stream_types, types

type_map = {
    "types.ExtractedMember": types.ExtractedMember,
    "stream_types.ExtractedMember": stream_types.ExtractedMember,
    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,
}
