# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

import typing_extensions
from pydantic import BaseModel

CheckT = typing_extensions.TypeVar("CheckT")
CheckName = typing_extensions.TypeVar("CheckName", bound=str)


class Check(BaseModel):
    name: str
    expression: str
    status: str


class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: dict[CheckName, Check]


def get_checks(checks: dict[CheckName, Check]) -> list[Check]:
    return list(checks.values())


def all_succeeded(checks: dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))


# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################


class ExtractedMember(BaseModel):
    name: str
    role: str | None = None
    party_name: str | None = None
    additional_info: str | None = None


class Resume(BaseModel):
    name: str
    email: str
    experience: list[str]
    skills: list[str]


# #########################################################################
# Generated type aliases (0)
# #########################################################################
